-- Generated by scripts/generate-supabase-seed.js. Do not edit manually.
begin;

truncate table
    public.course_images,
    public.category_courses,
    public.curriculum_shortcuts,
    public.portfolio_items,
    public.review_items,
    public.seminars,
    public.courses,
    public.curriculum_categories,
    public.app_settings
restart identity cascade;

insert into public.app_settings (key, value, is_published) values
    ('brand', '{"logoUrl":"https://se.sbsart.com/2022/img/common/logo.svg"}'::jsonb, true),
    ('location', '{"mapImage":"https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Map/Map_Img.png","mapAlt":"SBS아카데미컴퓨터아트학원 대전점 위치 지도","academyName":"SBS아카데미컴퓨터아트학원 대전점","addressLines":["대덕대로 179 굿모닝어학원빌딩 9층","sbs아카데미컴퓨터아트학원 대전점"],"subway":"시청역 2번 출구에서 타임월드 방향으로 10분거리","phone":"042-719-8383"}'::jsonb, true),
    ('contact', '{"phone":"042-719-8383","email":"privacy@koreaedugroup.com","blogUrl":"https://blog.naver.com/korea_sbs"}'::jsonb, true),
    ('seminar_meta', '{"applicationMethod":"스마트러닝 앱 → 메인페이지 화면 중앙(특강 및 세미나) → 원하는 세미나 클릭! → 하단 (특강&세미나) 신청","all":{"title":"Xgen / ACP 자격증 등","label":"특강 전체보기 →","url":"https://se.sbsart.com/community/seminar.asp?placeSeq=12"}}'::jsonb, true);

insert into public.curriculum_categories (slug, parent_slug, name, course_flow_html, sort_order, is_published) values
    ('design_basic', null, '디자인 기초', '일러스트,포토샵 > 디테일일러스트,포토웍스', 0, true),
    ('webtoon', null, '웹툰', '발상과 표현 > 색채학 > 해부학 > 포토샵/일러스트 > 포토웍스/디테일 일러스트 > 웹툰 1-6 > ComfyUI, Stable Diffusion > 웹툰 포폴', 1, true),
    ('artwork', null, '아트웍(드로잉)', '아트웍기초 > 발상과표현 > 색채학 > 해부학 > 포토샵/일러스트 > 포토웍스/디테일 일러스트 > 디지털 드로잉 1-6 > AI크리에이터 > ComfyUI, Stable Diffusion > 디지털 드로잉 포폴', 2, true),
    ('ai_agent', null, 'AI에이전트', '', 3, true),
    ('uiux', null, 'UIUX바이브', '발상과표현 > 색채학 > 포토샵/일러스트 > 포토웍스/디테일 일러스트 > 인포그래픽/그래픽아트웍 > 웹 1-3 > UIUX 1-3 > AI크리에이터-바이브코딩 > UIUX-스프린트 > 웹포폴 1-2', 4, true),
    ('ai_sw', null, '인공지능융합 SW', '파이썬 1-3 > 자바 1-2 > C언어 1-2 > 머신러닝 1-4', 5, true),
    ('visual', null, '시각편집디자인', '발상과표현 > 색채학 > 포토샵/일러스트 > 포토웍스/디테일 일러스트 > 인포그래픽/그래픽아트웍 > 인디자인 > AI크리에이터-시각편집 > 시각편집-비주얼 아트 디렉터 > 편집포폴 1-2', 6, true),
    ('archi', null, '건축, 인테리어', '발상과표현 > 색채학 > 포토샵/일러스트 > 포토웍스/디테일 일러스트 > 캐드 1-2 > 전산응용건축제도 기능사 > 스케치업 1-2 > 맥스 1-3 / Revit BIM(건축설계)1-2 > 시공실무 (기사/산업기사) > 실내건축자격증1-4 > AI크리에이터-인테리어 > 인테리어-ICG > 인테리어 포폴 1-3', 7, true),
    ('motion', null, '모션 그래픽', '발상과표현 > 색채학 > 포토샵/일러스트 > 포토웍스/디테일 일러스트 > 디지털 드로잉 1-6 > 프리미어 / 인포그래픽 > 애프터이펙트 / 그래픽아트웍 > 베이직에펙/모션 에펙 / 어드벤스 에펙 > 블렌더 1-2 / 시네마4D 1-4 > AI크리에이터-영상모션 / 스토리보드 > 모션-쇼릴 > 모션포폴 1-3', 8, true),
    ('cg_vfx', null, 'CG·VFX', '발상과표현 > 색채학 > 포토샵/일러스트 > 포토웍스/디테일 일러스트 > 디지털 드로잉 > 프리미어 > 베이직에펙/모션에펙/어드벤스에펙 > 블렌더 1-2 > 마야 1-7 > AI크리에이터 - CG/마야 / 스토리보드 > 마야-크리틱 > 마야포폴(VFX) 1-6', 9, true),
    ('youtube', null, '유튜브 크리에이터', '포토샵/일러스트 > AI크리에이터-유튜브 > 유튜브 기초 > 유튜브 심화 > 베이직에펙/모션에펙/어드벤스에펙', 10, true),
    ('product_cert', null, '제품/기계자격증', '캐드 1-2 > 퓨전360 1-2 > 인벤터 > 전산응용기계제도', 11, true),
    ('senior', null, '시니어', '컴퓨터기초 1-2', 12, true),
    ('cert', null, '자격증', '', 13, true),
    ('national', null, '국기', '국비 지원 과정별 상이 (상담 필요)', 14, true),
    ('ai_agent_basic', 'ai_agent', 'AI에이전트 (AI 기초)', 'AI 프롬프트엔지니어링1-2 > AI 에이전트 기초/심화 > AI 크리에이터', 0, true),
    ('ai_agent_advanced', 'ai_agent', 'AI에이전트 (AI 학과 심화)', 'AI 프롬프트엔지니어링1-2 > AI 에이전트 기초/심화 > AI 크리에이터', 1, true),
    ('cert_oa', 'cert', '자격증 (사무 OA)', 'MOS > 컴퓨터활용능력 1급/2급 > 전산회계 1급 > 전산세무 2급 > 재경관리사', 0, true),
    ('cert_field', 'cert', '자격증 (분야별)', 'ACP자격증 > GTQ·GTQi > 컴퓨터그래픽기능사 > 웹디자인개발기능사 > 컬러리스트 기사·산업기사 > AICE 자격증·AI-POT 자격 > 정보처리 기사·산업기사', 1, true);

insert into public.courses (name, is_published) values
    ('일러스트', true),
    ('포토웍스', true),
    ('포토샵', true),
    ('디테일일러스트', true),
    ('발상과 표현', true),
    ('색채학', true),
    ('해부학', true),
    ('웹툰 1-6', true),
    ('웹툰포폴', true),
    ('디지털드로잉1-6', true),
    ('인스타툰(금요특강)', true),
    ('AI프롬프트엔지니어링1-2', true),
    ('AI 에이전트 기초/심화', true),
    ('AI크리에이터 바이브코딩', true),
    ('AI크리에이터 아트웍', true),
    ('AI크리에이터 CG마야', true),
    ('AI크리에이터 인테리어', true),
    ('AI크리에이터 유튜브', true),
    ('AI크리에이터 영상모션', true),
    ('AI크리에이터 편집', true),
    ('AI크리에이터 웹툰(이미지 준비중)', true),
    ('웹1-3', true),
    ('UIUX1-3', true),
    ('UIUX 스프린트(포폴기획 - 금요특강)', true),
    ('웹포폴1-2', true),
    ('파이썬 1-3', true),
    ('자바 1-2', true),
    ('C언어 1-2', true),
    ('머신러닝 1-4(이미지 준비중)', true),
    ('인포그래픽', true),
    ('그래픽아트웍', true),
    ('인디자인', true),
    ('비주얼 아트 디렉터', true),
    ('편집포폴 1-2', true),
    ('캐드 1-2', true),
    ('전산응용건축제도', true),
    ('스케치업1-2', true),
    ('맥스 1-3', true),
    ('BIM1-2', true),
    ('실내건축자격증1-4&시공실무', true),
    ('인테리어 콘셉트 제네시스(포폴기획 - 금요특강)', true),
    ('인테리어 포폴 1-3', true),
    ('프리미어', true),
    ('베이직에펙', true),
    ('모션에펙', true),
    ('어드벤스에펙', true),
    ('숏폼컨텐츠(금요특강)', true),
    ('Blender1-2', true),
    ('시네마4D 1-4', true),
    ('스토리보드 1-6', true),
    ('모션 쇼릴(포폴기획 - 금요특강)', true),
    ('모션포폴 1-3', true),
    ('마야 1-7', true),
    ('스토리보드1-6', true),
    ('마야크리틱(포폴기획 - 금요특강)', true),
    ('마야포폴1-6', true),
    ('유튜브(영크리)', true),
    ('유튜브(시니어)', true),
    ('퓨전360 1-2(이미지 준비중)', true),
    ('인벤터', true),
    ('전산응용기계제도', true),
    ('컴퓨터기초(금요특강)', true),
    ('모스', true),
    ('컴활2급', true),
    ('컴활1급', true),
    ('전산회계1급', true),
    ('전산세무2급', true),
    ('재경관리사', true),
    ('실무엑셀(금요특강)(이미지 준비중)', true),
    ('GTQ/GTQi', true),
    ('컴퓨터그래픽기능사', true),
    ('웹디자인개발기능사', true),
    ('컬러리스트기사/산업기사', true),
    ('정보처리기사/산업기사(이미지 준비중)', true),
    ('AICE', true),
    ('정보처리기능사', true),
    ('편집디자인(포토샵, 일러스트, 인디자인) 실무자 양성과정', true),
    ('실내건축 인테리어 과정(CAD, 스케치업)', true),
    ('영상편집&유튜브편집제작(프리미어,에프터이펙트)실무자 양성과정', true),
    ('[BIM] 스마트 건축 설계&실내인테리어 3D디자이너 양성과정(캐드,스케치업,레빗)', true),
    ('[디지털디자인] AI 기반 UIUX 웹디자인 & 웹퍼블리셔 양성과정(Figma, HTML5, CSS)', true),
    ('[디지털컨버전스] 공공데이터 융합 풀스택 웹 개발자 양성과정(Next.js & Spring)', true),
    ('[과정평가형] 실내건축기능사 취득과정 (캐드,스케치업)', true),
    ('GTQ', true),
    ('유튜브', true);

insert into public.category_courses (category_slug, course_id, sort_order, is_published)
select 'design_basic', id, course_order, true
from public.courses
join (values
    ('일러스트', 0),
    ('포토웍스', 1),
    ('포토샵', 2),
    ('디테일일러스트', 3)
) as source(course_name, course_order) on source.course_name = courses.name;

insert into public.category_courses (category_slug, course_id, sort_order, is_published)
select 'webtoon', id, course_order, true
from public.courses
join (values
    ('발상과 표현', 0),
    ('색채학', 1),
    ('해부학', 2),
    ('웹툰 1-6', 3),
    ('웹툰포폴', 4)
) as source(course_name, course_order) on source.course_name = courses.name;

insert into public.category_courses (category_slug, course_id, sort_order, is_published)
select 'artwork', id, course_order, true
from public.courses
join (values
    ('디지털드로잉1-6', 0),
    ('발상과 표현', 1),
    ('색채학', 2),
    ('해부학', 3),
    ('인스타툰(금요특강)', 4)
) as source(course_name, course_order) on source.course_name = courses.name;

insert into public.category_courses (category_slug, course_id, sort_order, is_published)
select 'ai_agent_basic', id, course_order, true
from public.courses
join (values
    ('AI프롬프트엔지니어링1-2', 0),
    ('AI 에이전트 기초/심화', 1)
) as source(course_name, course_order) on source.course_name = courses.name;

insert into public.category_courses (category_slug, course_id, sort_order, is_published)
select 'ai_agent_advanced', id, course_order, true
from public.courses
join (values
    ('AI크리에이터 바이브코딩', 0),
    ('AI크리에이터 아트웍', 1),
    ('AI크리에이터 CG마야', 2),
    ('AI크리에이터 인테리어', 3),
    ('AI크리에이터 유튜브', 4),
    ('AI크리에이터 영상모션', 5),
    ('AI크리에이터 편집', 6),
    ('AI크리에이터 웹툰(이미지 준비중)', 7)
) as source(course_name, course_order) on source.course_name = courses.name;

insert into public.category_courses (category_slug, course_id, sort_order, is_published)
select 'uiux', id, course_order, true
from public.courses
join (values
    ('웹1-3', 0),
    ('UIUX1-3', 1),
    ('UIUX 스프린트(포폴기획 - 금요특강)', 2),
    ('웹포폴1-2', 3)
) as source(course_name, course_order) on source.course_name = courses.name;

insert into public.category_courses (category_slug, course_id, sort_order, is_published)
select 'ai_sw', id, course_order, true
from public.courses
join (values
    ('파이썬 1-3', 0),
    ('자바 1-2', 1),
    ('C언어 1-2', 2),
    ('머신러닝 1-4(이미지 준비중)', 3)
) as source(course_name, course_order) on source.course_name = courses.name;

insert into public.category_courses (category_slug, course_id, sort_order, is_published)
select 'visual', id, course_order, true
from public.courses
join (values
    ('인포그래픽', 0),
    ('그래픽아트웍', 1),
    ('인디자인', 2),
    ('비주얼 아트 디렉터', 3),
    ('편집포폴 1-2', 4)
) as source(course_name, course_order) on source.course_name = courses.name;

insert into public.category_courses (category_slug, course_id, sort_order, is_published)
select 'archi', id, course_order, true
from public.courses
join (values
    ('캐드 1-2', 0),
    ('전산응용건축제도', 1),
    ('스케치업1-2', 2),
    ('맥스 1-3', 3),
    ('BIM1-2', 4),
    ('실내건축자격증1-4&시공실무', 5),
    ('인테리어 콘셉트 제네시스(포폴기획 - 금요특강)', 6),
    ('인테리어 포폴 1-3', 7)
) as source(course_name, course_order) on source.course_name = courses.name;

insert into public.category_courses (category_slug, course_id, sort_order, is_published)
select 'motion', id, course_order, true
from public.courses
join (values
    ('프리미어', 0),
    ('베이직에펙', 1),
    ('모션에펙', 2),
    ('어드벤스에펙', 3),
    ('숏폼컨텐츠(금요특강)', 4),
    ('Blender1-2', 5),
    ('시네마4D 1-4', 6),
    ('스토리보드 1-6', 7),
    ('모션 쇼릴(포폴기획 - 금요특강)', 8),
    ('모션포폴 1-3', 9)
) as source(course_name, course_order) on source.course_name = courses.name;

insert into public.category_courses (category_slug, course_id, sort_order, is_published)
select 'cg_vfx', id, course_order, true
from public.courses
join (values
    ('프리미어', 0),
    ('베이직에펙', 1),
    ('모션에펙', 2),
    ('어드벤스에펙', 3),
    ('Blender1-2', 4),
    ('마야 1-7', 5),
    ('스토리보드1-6', 6),
    ('마야크리틱(포폴기획 - 금요특강)', 7),
    ('마야포폴1-6', 8)
) as source(course_name, course_order) on source.course_name = courses.name;

insert into public.category_courses (category_slug, course_id, sort_order, is_published)
select 'youtube', id, course_order, true
from public.courses
join (values
    ('프리미어', 0),
    ('베이직에펙', 1),
    ('모션에펙', 2),
    ('어드벤스에펙', 3),
    ('유튜브(영크리)', 4),
    ('유튜브(시니어)', 5),
    ('숏폼컨텐츠(금요특강)', 6)
) as source(course_name, course_order) on source.course_name = courses.name;

insert into public.category_courses (category_slug, course_id, sort_order, is_published)
select 'product_cert', id, course_order, true
from public.courses
join (values
    ('캐드 1-2', 0),
    ('퓨전360 1-2(이미지 준비중)', 1),
    ('인벤터', 2),
    ('전산응용기계제도', 3)
) as source(course_name, course_order) on source.course_name = courses.name;

insert into public.category_courses (category_slug, course_id, sort_order, is_published)
select 'senior', id, course_order, true
from public.courses
join (values
    ('컴퓨터기초(금요특강)', 0)
) as source(course_name, course_order) on source.course_name = courses.name;

insert into public.category_courses (category_slug, course_id, sort_order, is_published)
select 'cert_oa', id, course_order, true
from public.courses
join (values
    ('모스', 0),
    ('컴활2급', 1),
    ('컴활1급', 2),
    ('전산회계1급', 3),
    ('전산세무2급', 4),
    ('재경관리사', 5),
    ('실무엑셀(금요특강)(이미지 준비중)', 6)
) as source(course_name, course_order) on source.course_name = courses.name;

insert into public.category_courses (category_slug, course_id, sort_order, is_published)
select 'cert_field', id, course_order, true
from public.courses
join (values
    ('GTQ/GTQi', 0),
    ('컴퓨터그래픽기능사', 1),
    ('웹디자인개발기능사', 2),
    ('컬러리스트기사/산업기사', 3),
    ('정보처리기사/산업기사(이미지 준비중)', 4),
    ('AICE', 5),
    ('정보처리기능사', 6)
) as source(course_name, course_order) on source.course_name = courses.name;

insert into public.category_courses (category_slug, course_id, sort_order, is_published)
select 'national', id, course_order, true
from public.courses
join (values
    ('편집디자인(포토샵, 일러스트, 인디자인) 실무자 양성과정', 0),
    ('실내건축 인테리어 과정(CAD, 스케치업)', 1),
    ('영상편집&유튜브편집제작(프리미어,에프터이펙트)실무자 양성과정', 2),
    ('[BIM] 스마트 건축 설계&실내인테리어 3D디자이너 양성과정(캐드,스케치업,레빗)', 3),
    ('[디지털디자인] AI 기반 UIUX 웹디자인 & 웹퍼블리셔 양성과정(Figma, HTML5, CSS)', 4),
    ('[디지털컨버전스] 공공데이터 융합 풀스택 웹 개발자 양성과정(Next.js & Spring)', 5),
    ('[과정평가형] 실내건축기능사 취득과정 (캐드,스케치업)', 6)
) as source(course_name, course_order) on source.course_name = courses.name;

insert into public.course_images (course_id, image_url, alt_text, sort_order, is_published)
select courses.id, source.image_url, 'AI프롬프트엔지니어링1-2 과정 상세 이미지', source.image_order, true
from public.courses
cross join (values
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/AI_Prompt_Engineering/AI_Prompt_Engineering2.jpg', 0),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/AI_Prompt_Engineering/AI_Prompt_Engineering3.jpg', 1),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/AI_Prompt_Engineering/AI_Prompt_Engineering4.jpg', 2),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/AI_Prompt_Engineering/AI_Prompt_Engineering5.jpg', 3),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/AI_Prompt_Engineering/AI_Prompt_Engineering6.jpg', 4)
) as source(image_url, image_order)
where courses.name = 'AI프롬프트엔지니어링1-2';

insert into public.course_images (course_id, image_url, alt_text, sort_order, is_published)
select courses.id, source.image_url, 'GTQ 과정 상세 이미지', source.image_order, true
from public.courses
cross join (values
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/GTQ/GTQ2.jpg', 0),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/GTQ/GTQ3.jpg', 1),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/GTQ/GTQ4.jpg', 2),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/GTQ/GTQ5.jpg', 3)
) as source(image_url, image_order)
where courses.name = 'GTQ';

insert into public.course_images (course_id, image_url, alt_text, sort_order, is_published)
select courses.id, source.image_url, '그래픽아트웍 과정 상세 이미지', source.image_order, true
from public.courses
cross join (values
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Graphic_artwork/Graphic_artwork2.jpg', 0),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Graphic_artwork/Graphic_artwork3.jpg', 1),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Graphic_artwork/Graphic_artwork4.jpg', 2),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Graphic_artwork/Graphic_artwork5.jpg', 3)
) as source(image_url, image_order)
where courses.name = '그래픽아트웍';

insert into public.course_images (course_id, image_url, alt_text, sort_order, is_published)
select courses.id, source.image_url, 'GTQ/GTQi 과정 상세 이미지', source.image_order, true
from public.courses
cross join (values
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/GTQi/GTQi2.jpg', 0),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/GTQi/GTQi3.jpg', 1),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/GTQi/GTQi4.jpg', 2),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/GTQi/GTQi5.jpg', 3)
) as source(image_url, image_order)
where courses.name = 'GTQ/GTQi';

insert into public.course_images (course_id, image_url, alt_text, sort_order, is_published)
select courses.id, source.image_url, '디지털드로잉1-6 과정 상세 이미지', source.image_order, true
from public.courses
cross join (values
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Digital_Drawing/Digital_Drawing3.jpg', 0),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Digital_Drawing/Digital_Drawing4.jpg', 1),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Digital_Drawing/Digital_Drawing5.jpg', 2),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Digital_Drawing/Digital_Drawing6.jpg', 3),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Digital_Drawing/Digital_Drawing7.jpg', 4),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Digital_Drawing/Digital_Drawing8.jpg', 5),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Digital_Drawing/Digital_Drawing9.jpg', 6),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Digital_Drawing/Digital_Drawing10.jpg', 7),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Digital_Drawing/Digital_Drawing11.jpg', 8),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Digital_Drawing/Digital_Drawing12.jpg', 9),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Digital_Drawing/Digital_Drawing13.jpg', 10),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Digital_Drawing/Digital_Drawing14.jpg', 11),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Digital_Drawing/Digital_Drawing15.jpg', 12)
) as source(image_url, image_order)
where courses.name = '디지털드로잉1-6';

insert into public.course_images (course_id, image_url, alt_text, sort_order, is_published)
select courses.id, source.image_url, '해부학 과정 상세 이미지', source.image_order, true
from public.courses
cross join (values
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Anatomy/Anatomy2.jpg', 0),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Anatomy/Anatomy3.jpg', 1),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Anatomy/Anatomy4.jpg', 2),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Anatomy/Anatomy5.jpg', 3),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Anatomy/Anatomy6.jpg', 4)
) as source(image_url, image_order)
where courses.name = '해부학';

insert into public.course_images (course_id, image_url, alt_text, sort_order, is_published)
select courses.id, source.image_url, '일러스트 과정 상세 이미지', source.image_order, true
from public.courses
cross join (values
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/illustration/illustration2.jpg', 0),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/illustration/illustration3.jpg', 1),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/illustration/illustration4.jpg', 2),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/illustration/illustration5.jpg', 3)
) as source(image_url, image_order)
where courses.name = '일러스트';

insert into public.course_images (course_id, image_url, alt_text, sort_order, is_published)
select courses.id, source.image_url, '인디자인 과정 상세 이미지', source.image_order, true
from public.courses
cross join (values
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/InDesign/InDesign2.jpg', 0),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/InDesign/InDesign3.jpg', 1),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/InDesign/InDesign4.jpg', 2),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/InDesign/InDesign5.jpg', 3)
) as source(image_url, image_order)
where courses.name = '인디자인';

insert into public.course_images (course_id, image_url, alt_text, sort_order, is_published)
select courses.id, source.image_url, '인스타툰(금요특강) 과정 상세 이미지', source.image_order, true
from public.courses
cross join (values
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Instagram_Toon/Instagram_Toon2.jpg', 0),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Instagram_Toon/Instagram_Toon3.jpg', 1),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Instagram_Toon/Instagram_Toon4.jpg', 2)
) as source(image_url, image_order)
where courses.name = '인스타툰(금요특강)';

insert into public.course_images (course_id, image_url, alt_text, sort_order, is_published)
select courses.id, source.image_url, '인포그래픽 과정 상세 이미지', source.image_order, true
from public.courses
cross join (values
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Infographic/Infographic2.jpg', 0),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Infographic/Infographic3.jpg', 1),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Infographic/Infographic4.jpg', 2),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Infographic/Infographic5.jpg', 3)
) as source(image_url, image_order)
where courses.name = '인포그래픽';

insert into public.course_images (course_id, image_url, alt_text, sort_order, is_published)
select courses.id, source.image_url, 'AI 에이전트 기초/심화 과정 상세 이미지', source.image_order, true
from public.courses
cross join (values
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/AI_Agent/AI_Agent2.jpg', 0),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/AI_Agent/AI_Agent3.jpg', 1),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/AI_Agent/AI_Agent4.jpg', 2),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/AI_Agents_Deep/AI_Agents_Deepening2.jpg', 3),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/AI_Agents_Deep/AI_Agents_Deepening3.jpg', 4),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/AI_Agents_Deep/AI_Agents_Deepening4.jpg', 5)
) as source(image_url, image_order)
where courses.name = 'AI 에이전트 기초/심화';

insert into public.course_images (course_id, image_url, alt_text, sort_order, is_published)
select courses.id, source.image_url, 'AI크리에이터 편집 과정 상세 이미지', source.image_order, true
from public.courses
cross join (values
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Edit_AI_Creator/Edit_AI_Creator2.jpg', 0),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Edit_AI_Creator/Edit_AI_Creator3.jpg', 1),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Edit_AI_Creator/Edit_AI_Creator4.jpg', 2),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Edit_AI_Creator/Edit_AI_Creator5.jpg', 3)
) as source(image_url, image_order)
where courses.name = 'AI크리에이터 편집';

insert into public.course_images (course_id, image_url, alt_text, sort_order, is_published)
select courses.id, source.image_url, 'AI크리에이터 CG마야 과정 상세 이미지', source.image_order, true
from public.courses
cross join (values
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/CGAI_Creator_CGMaya/CGAI_Creator_CGMaya2.jpg', 0),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/CGAI_Creator_CGMaya/CGAI_Creator_CGMaya3.jpg', 1),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/CGAI_Creator_CGMaya/CGAI_Creator_CGMaya4.jpg', 2),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/CGAI_Creator_CGMaya/CGAI_Creator_CGMaya5.jpg', 3)
) as source(image_url, image_order)
where courses.name = 'AI크리에이터 CG마야';

insert into public.course_images (course_id, image_url, alt_text, sort_order, is_published)
select courses.id, source.image_url, 'AI크리에이터 바이브코딩 과정 상세 이미지', source.image_order, true
from public.courses
cross join (values
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/VibeAI/VibeAI_Creator_Vibe%20Coding2.jpg', 0),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/VibeAI/VibeAI_Creator_Vibe%20Coding3.jpg', 1),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/VibeAI/VibeAI_Creator_Vibe%20Coding4.jpg', 2),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/VibeAI/VibeAI_Creator_Vibe%20Coding5.jpg', 3)
) as source(image_url, image_order)
where courses.name = 'AI크리에이터 바이브코딩';

insert into public.course_images (course_id, image_url, alt_text, sort_order, is_published)
select courses.id, source.image_url, 'AI크리에이터 아트웍 과정 상세 이미지', source.image_order, true
from public.courses
cross join (values
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/AI_Creator_Artwork/AI_Creator_Artwork2.jpg', 0),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/AI_Creator_Artwork/AI_Creator_Artwork3.jpg', 1),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/AI_Creator_Artwork/AI_Creator_Artwork4.jpg', 2),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/AI_Creator_Artwork/AI_Creator_Artwork5.jpg', 3)
) as source(image_url, image_order)
where courses.name = 'AI크리에이터 아트웍';

insert into public.course_images (course_id, image_url, alt_text, sort_order, is_published)
select courses.id, source.image_url, 'AI크리에이터 인테리어 과정 상세 이미지', source.image_order, true
from public.courses
cross join (values
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/AI_Creator_Interior/AI_Creator_Interior2.jpg', 0),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/AI_Creator_Interior/AI_Creator_Interior3.jpg', 1),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/AI_Creator_Interior/AI_Creator_Interior4.jpg', 2),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/AI_Creator_Interior/AI_Creator_Interior5.jpg', 3)
) as source(image_url, image_order)
where courses.name = 'AI크리에이터 인테리어';

insert into public.course_images (course_id, image_url, alt_text, sort_order, is_published)
select courses.id, source.image_url, 'AI크리에이터 유튜브 과정 상세 이미지', source.image_order, true
from public.courses
cross join (values
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/AI_Creator_YouTube/AI_Creator_YouTube2.jpg', 0),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/AI_Creator_YouTube/AI_Creator_YouTube3.jpg', 1),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/AI_Creator_YouTube/AI_Creator_YouTube4.jpg', 2),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/AI_Creator_YouTube/AI_Creator_YouTube5.jpg', 3)
) as source(image_url, image_order)
where courses.name = 'AI크리에이터 유튜브';

insert into public.course_images (course_id, image_url, alt_text, sort_order, is_published)
select courses.id, source.image_url, 'AI크리에이터 영상모션 과정 상세 이미지', source.image_order, true
from public.courses
cross join (values
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/AI_Creator_Video_Motion/AI_Creator_Video_Motion2.jpg', 0),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/AI_Creator_Video_Motion/AI_Creator_Video_Motion3.jpg', 1),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/AI_Creator_Video_Motion/AI_Creator_Video_Motion4.jpg', 2),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/AI_Creator_Video_Motion/AI_Creator_Video_Motion5.jpg', 3)
) as source(image_url, image_order)
where courses.name = 'AI크리에이터 영상모션';

insert into public.course_images (course_id, image_url, alt_text, sort_order, is_published)
select courses.id, source.image_url, '[BIM] 스마트 건축 설계&실내인테리어 3D디자이너 양성과정(캐드,스케치업,레빗) 과정 상세 이미지', source.image_order, true
from public.courses
cross join (values
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/AaABIM/BIM_AaABIM_Architecture%20and%20Architectural2.jpg', 0),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/AaABIM/BIM_AaABIM_Architecture%20and%20Architectural3.jpg', 1),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/AaABIM/BIM_AaABIM_Architecture%20and%20Architectural4.jpg', 2),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/AaABIM/BIM_AaABIM_Architecture%20and%20Architectural5.jpg', 3),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/AaABIM/BIM_AaABIM_Architecture%20and%20Architectural6.jpg', 4),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/AaABIM/BIM_AaABIM_Architecture%20and%20Architectural7.jpg', 5),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/AaABIM/BIM_AaABIM_Architecture%20and%20Architectural8.jpg', 6),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/AaABIM/BIM_AaABIM_Architecture%20and%20Architectural9.jpg', 7),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/AaABIM/BIM_AaABIM_Architecture%20and%20Architectural10.jpg', 8),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/AaABIM/BIM_AaABIM_Architecture%20and%20Architectural11.jpg', 9),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/AaABIM/BIM_AaABIM_Architecture%20and%20Architectural12.jpg', 10),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/AaABIM/BIM_AaABIM_Architecture%20and%20Architectural13.jpg', 11),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/AaABIM/BIM_AaABIM_Architecture%20and%20Architectural14.jpg', 12),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/AaABIM/BIM_AaABIM_Architecture%20and%20Architectural15.jpg', 13)
) as source(image_url, image_order)
where courses.name = '[BIM] 스마트 건축 설계&실내인테리어 3D디자이너 양성과정(캐드,스케치업,레빗)';

insert into public.course_images (course_id, image_url, alt_text, sort_order, is_published)
select courses.id, source.image_url, 'UIUX 스프린트(포폴기획 - 금요특강) 과정 상세 이미지', source.image_order, true
from public.courses
cross join (values
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/SprintUIUX/SprintUIUX_Sprint2.jpg', 0),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/SprintUIUX/SprintUIUX_Sprint3.jpg', 1),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/SprintUIUX/SprintUIUX_Sprint4.jpg', 2),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/SprintUIUX/SprintUIUX_Sprint5.jpg', 3)
) as source(image_url, image_order)
where courses.name = 'UIUX 스프린트(포폴기획 - 금요특강)';

insert into public.course_images (course_id, image_url, alt_text, sort_order, is_published)
select courses.id, source.image_url, '[디지털디자인] AI 기반 UIUX 웹디자인 & 웹퍼블리셔 양성과정(Figma, HTML5, CSS) 과정 상세 이미지', source.image_order, true
from public.courses
cross join (values
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/UIUX_FrontEnd/UIUX_FrontEnd2.jpg', 0),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/UIUX_FrontEnd/UIUX_FrontEnd3.jpg', 1),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/UIUX_FrontEnd/UIUX_FrontEnd4.jpg', 2),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/UIUX_FrontEnd/UIUX_FrontEnd5.jpg', 3),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/UIUX_FrontEnd/UIUX_FrontEnd6.jpg', 4),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/UIUX_FrontEnd/UIUX_FrontEnd7.jpg', 5),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/UIUX_FrontEnd/UIUX_FrontEnd8.jpg', 6),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/UIUX_FrontEnd/UIUX_FrontEnd9.jpg', 7),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/UIUX_FrontEnd/UIUX_FrontEnd10.jpg', 8),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/UIUX_FrontEnd/UIUX_FrontEnd11.jpg', 9)
) as source(image_url, image_order)
where courses.name = '[디지털디자인] AI 기반 UIUX 웹디자인 & 웹퍼블리셔 양성과정(Figma, HTML5, CSS)';

insert into public.course_images (course_id, image_url, alt_text, sort_order, is_published)
select courses.id, source.image_url, '모션 쇼릴(포폴기획 - 금요특강) 과정 상세 이미지', source.image_order, true
from public.courses
cross join (values
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Motion_showreel/Motion_showreel2.jpg', 0),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Motion_showreel/Motion_showreel3.jpg', 1),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Motion_showreel/Motion_showreel4.jpg', 2),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Motion_showreel/Motion_showreel5.jpg', 3),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Motion_showreel/Motion_showreel6.jpg', 4)
) as source(image_url, image_order)
where courses.name = '모션 쇼릴(포폴기획 - 금요특강)';

insert into public.course_images (course_id, image_url, alt_text, sort_order, is_published)
select courses.id, source.image_url, '비주얼 아트 디렉터 과정 상세 이미지', source.image_order, true
from public.courses
cross join (values
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Art_director/Art_director2.jpg', 0),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Art_director/Art_director3.jpg', 1),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Art_director/Art_director4.jpg', 2),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Art_director/Art_director5.jpg', 3)
) as source(image_url, image_order)
where courses.name = '비주얼 아트 디렉터';

insert into public.course_images (course_id, image_url, alt_text, sort_order, is_published)
select courses.id, source.image_url, '[디지털컨버전스] 공공데이터 융합 풀스택 웹 개발자 양성과정(Next.js & Spring) 과정 상세 이미지', source.image_order, true
from public.courses
cross join (values
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Fullstec/Fullstec2.jpg', 0),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Fullstec/Fullstec3.jpg', 1),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Fullstec/Fullstec4.jpg', 2),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Fullstec/Fullstec5.jpg', 3),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Fullstec/Fullstec6.jpg', 4),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Fullstec/Fullstec7.jpg', 5),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Fullstec/Fullstec8.jpg', 6),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Fullstec/Fullstec9.jpg', 7),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Fullstec/Fullstec10.jpg', 8),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Fullstec/Fullstec11.jpg', 9),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Fullstec/Fullstec12.jpg', 10),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Fullstec/Fullstec13.jpg', 11),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Fullstec/Fullstec14.jpg', 12),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Fullstec/Fullstec15.jpg', 13)
) as source(image_url, image_order)
where courses.name = '[디지털컨버전스] 공공데이터 융합 풀스택 웹 개발자 양성과정(Next.js & Spring)';

insert into public.course_images (course_id, image_url, alt_text, sort_order, is_published)
select courses.id, source.image_url, '웹툰 1-6 과정 상세 이미지', source.image_order, true
from public.courses
cross join (values
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Webtoon/1777000613257-6204d25a-661a-445c-a3b6-50fa51e652eb_3.jpg', 0),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Webtoon/1777000613257-6204d25a-661a-445c-a3b6-50fa51e652eb_4.jpg', 1),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Webtoon/1777000613257-6204d25a-661a-445c-a3b6-50fa51e652eb_5.jpg', 2),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Webtoon/1777000613257-6204d25a-661a-445c-a3b6-50fa51e652eb_6.jpg', 3),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Webtoon/1777000613257-6204d25a-661a-445c-a3b6-50fa51e652eb_7.jpg', 4),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Webtoon/1777000613257-6204d25a-661a-445c-a3b6-50fa51e652eb_8.jpg', 5),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Webtoon/1777000613257-6204d25a-661a-445c-a3b6-50fa51e652eb_9.jpg', 6),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Webtoon/1777000613257-6204d25a-661a-445c-a3b6-50fa51e652eb_10.jpg', 7),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Webtoon/1777000613257-6204d25a-661a-445c-a3b6-50fa51e652eb_11.jpg', 8),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Webtoon/1777000613257-6204d25a-661a-445c-a3b6-50fa51e652eb_12.jpg', 9),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Webtoon/1777000613257-6204d25a-661a-445c-a3b6-50fa51e652eb_13.jpg', 10),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Webtoon/1777000613257-6204d25a-661a-445c-a3b6-50fa51e652eb_14.jpg', 11),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Webtoon/1777000613257-6204d25a-661a-445c-a3b6-50fa51e652eb_15.jpg', 12)
) as source(image_url, image_order)
where courses.name = '웹툰 1-6';

insert into public.course_images (course_id, image_url, alt_text, sort_order, is_published)
select courses.id, source.image_url, '인테리어 콘셉트 제네시스(포폴기획 - 금요특강) 과정 상세 이미지', source.image_order, true
from public.courses
cross join (values
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Genesis/Genesis2.jpg', 0),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Genesis/Genesis3.jpg', 1),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Genesis/Genesis4.jpg', 2),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Genesis/Genesis5.jpg', 3)
) as source(image_url, image_order)
where courses.name = '인테리어 콘셉트 제네시스(포폴기획 - 금요특강)';

insert into public.course_images (course_id, image_url, alt_text, sort_order, is_published)
select courses.id, source.image_url, '정보처리기능사 과정 상세 이미지', source.image_order, true
from public.courses
cross join (values
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Information_processing_technician/Information_processing_technician2.jpg', 0),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Information_processing_technician/Information_processing_technician3.jpg', 1),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Information_processing_technician/Information_processing_technician4.jpg', 2),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Information_processing_technician/Information_processing_technician5.jpg', 3),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Information_processing_technician/Information_processing_technician6.jpg', 4),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Information_processing_technician/Information_processing_technician7.jpg', 5),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Information_processing_technician/Information_processing_technician8.jpg', 6),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Information_processing_technician/Information_processing_technician9.jpg', 7),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Information_processing_technician/Information_processing_technician10.jpg', 8),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Information_processing_technician/Information_processing_technician11.jpg', 9),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Information_processing_technician/Information_processing_technician12.jpg', 10),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Information_processing_technician/Information_processing_technician13.jpg', 11)
) as source(image_url, image_order)
where courses.name = '정보처리기능사';

insert into public.course_images (course_id, image_url, alt_text, sort_order, is_published)
select courses.id, source.image_url, '정보처리기사/산업기사(이미지 준비중) 과정 상세 이미지', source.image_order, true
from public.courses
cross join (values
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/An_information_processing_industry_engineer/An_information_processing_industry_engineer2.jpg', 0),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/An_information_processing_industry_engineer/An_information_processing_industry_engineer3.jpg', 1),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/An_information_processing_industry_engineer/An_information_processing_industry_engineer4.jpg', 2),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/An_information_processing_industry_engineer/An_information_processing_industry_engineer5.jpg', 3),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/An_information_processing_industry_engineer/An_information_processing_industry_engineer6.jpg', 4),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/An_information_processing_industry_engineer/An_information_processing_industry_engineer8.jpg', 5),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/An_information_processing_industry_engineer/An_information_processing_industry_engineer9.jpg', 6),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/An_information_processing_industry_engineer/An_information_processing_industry_engineer10.jpg', 7),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/An_information_processing_industry_engineer/An_information_processing_industry_engineer11.jpg', 8),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/An_information_processing_industry_engineer/An_information_processing_industry_engineer12.jpg', 9),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/An_information_processing_industry_engineer/An_information_processing_industry_engineer13.jpg', 10),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/An_information_processing_industry_engineer/An_information_processing_industry_engineer14.jpg', 11),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/An_information_processing_industry_engineer/An_information_processing_industry_engineer15.jpg', 12),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/An_information_processing_industry_engineer/An_information_processing_industry_engineer16.jpg', 13)
) as source(image_url, image_order)
where courses.name = '정보처리기사/산업기사(이미지 준비중)';

insert into public.course_images (course_id, image_url, alt_text, sort_order, is_published)
select courses.id, source.image_url, '캐드 1-2 과정 상세 이미지', source.image_order, true
from public.courses
cross join (values
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/CAD/CAD2.jpg', 0),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/CAD/CAD3.jpg', 1),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/CAD/CAD4.jpg', 2),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/CAD/CAD5.jpg', 3),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/CAD/CAD6.jpg', 4),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/CAD/CAD7.jpg', 5),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/CAD/CAD8.jpg', 6),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/CAD/CAD9.jpg', 7)
) as source(image_url, image_order)
where courses.name = '캐드 1-2';

insert into public.course_images (course_id, image_url, alt_text, sort_order, is_published)
select courses.id, source.image_url, '컴퓨터기초(금요특강) 과정 상세 이미지', source.image_order, true
from public.courses
cross join (values
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Basics_computer/Basics_computer2.jpg', 0),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Basics_computer/Basics_computer3.jpg', 1),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Basics_computer/Basics_computer4.jpg', 2),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Basics_computer/Basics_computer5.jpg', 3),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Basics_computer/Basics_computer6.jpg', 4)
) as source(image_url, image_order)
where courses.name = '컴퓨터기초(금요특강)';

insert into public.course_images (course_id, image_url, alt_text, sort_order, is_published)
select courses.id, source.image_url, '컴활2급 과정 상세 이미지', source.image_order, true
from public.courses
cross join (values
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/computer_skills2/computer_skills2_2.jpg', 0),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/computer_skills2/computer_skills2_3.jpg', 1),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/computer_skills2/computer_skills2_4.jpg', 2),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/computer_skills2/computer_skills2_5.jpg', 3)
) as source(image_url, image_order)
where courses.name = '컴활2급';

insert into public.course_images (course_id, image_url, alt_text, sort_order, is_published)
select courses.id, source.image_url, '컴활1급 과정 상세 이미지', source.image_order, true
from public.courses
cross join (values
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Computer_literacy_1level/Computer_literacy_1level3.jpg', 0),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Computer_literacy_1level/Computer_literacy_1level4.jpg', 1),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Computer_literacy_1level/Computer_literacy_1level5.jpg', 2),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Computer_literacy_1level/Computer_literacy_1level6.jpg', 3)
) as source(image_url, image_order)
where courses.name = '컴활1급';

insert into public.course_images (course_id, image_url, alt_text, sort_order, is_published)
select courses.id, source.image_url, '전산회계1급 과정 상세 이미지', source.image_order, true
from public.courses
cross join (values
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Computerized_Accounting_1Class/Computerized_Accounting_1Class3.jpg', 0),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Computerized_Accounting_1Class/Computerized_Accounting_1Class4.jpg', 1),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Computerized_Accounting_1Class/Computerized_Accounting_1Class5.jpg', 2),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Computerized_Accounting_1Class/Computerized_Accounting_1Class6.jpg', 3),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Computerized_Accounting_1Class/Computerized_Accounting_1Class7.jpg', 4)
) as source(image_url, image_order)
where courses.name = '전산회계1급';

insert into public.course_images (course_id, image_url, alt_text, sort_order, is_published)
select courses.id, source.image_url, '전산세무2급 과정 상세 이미지', source.image_order, true
from public.courses
cross join (values
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Computerized_tax_2level/Computerized_tax_2level3.jpg', 0),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Computerized_tax_2level/Computerized_tax_2level4.jpg', 1),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Computerized_tax_2level/Computerized_tax_2level5.jpg', 2),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Computerized_tax_2level/Computerized_tax_2level6.jpg', 3),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Computerized_tax_2level/Computerized_tax_2level7.jpg', 4)
) as source(image_url, image_order)
where courses.name = '전산세무2급';

insert into public.course_images (course_id, image_url, alt_text, sort_order, is_published)
select courses.id, source.image_url, '재경관리사 과정 상세 이미지', source.image_order, true
from public.courses
cross join (values
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Financial_Manager/Financial_Manager2.jpg', 0),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Financial_Manager/Financial_Manager3.jpg', 1),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Financial_Manager/Financial_Manager4.jpg', 2),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Financial_Manager/Financial_Manager5.jpg', 3)
) as source(image_url, image_order)
where courses.name = '재경관리사';

insert into public.course_images (course_id, image_url, alt_text, sort_order, is_published)
select courses.id, source.image_url, '전산응용기계제도 과정 상세 이미지', source.image_order, true
from public.courses
cross join (values
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Computerized_Application_Mechanical_System/Computerized_Application_Mechanical_System2.jpg', 0),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Computerized_Application_Mechanical_System/Computerized_Application_Mechanical_System3.jpg', 1),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Computerized_Application_Mechanical_System/Computerized_Application_Mechanical_System4.jpg', 2),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Computerized_Application_Mechanical_System/Computerized_Application_Mechanical_System5.jpg', 3),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Computerized_Application_Mechanical_System/Computerized_Application_Mechanical_System6.jpg', 4)
) as source(image_url, image_order)
where courses.name = '전산응용기계제도';

insert into public.course_images (course_id, image_url, alt_text, sort_order, is_published)
select courses.id, source.image_url, '전산응용건축제도 과정 상세 이미지', source.image_order, true
from public.courses
cross join (values
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Computer-Applied_Building_System/Computer-Applied_Building_System2.jpg', 0),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Computer-Applied_Building_System/Computer-Applied_Building_System3.jpg', 1),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Computer-Applied_Building_System/Computer-Applied_Building_System4.jpg', 2)
) as source(image_url, image_order)
where courses.name = '전산응용건축제도';

insert into public.course_images (course_id, image_url, alt_text, sort_order, is_published)
select courses.id, source.image_url, '인벤터 과정 상세 이미지', source.image_order, true
from public.courses
cross join (values
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Inventory/Inventory2.jpg', 0),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Inventory/Inventory3.jpg', 1),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Inventory/Inventory4.jpg', 2),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Inventory/Inventory5.jpg', 3)
) as source(image_url, image_order)
where courses.name = '인벤터';

insert into public.course_images (course_id, image_url, alt_text, sort_order, is_published)
select courses.id, source.image_url, '파이썬 1-3 과정 상세 이미지', source.image_order, true
from public.courses
cross join (values
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Python/Python2.jpg', 0),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Python/Python3.jpg', 1),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Python/Python4.jpg', 2),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Python/Python5.jpg', 3),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Python/Python6.jpg', 4),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Python/Python7.jpg', 5)
) as source(image_url, image_order)
where courses.name = '파이썬 1-3';

insert into public.course_images (course_id, image_url, alt_text, sort_order, is_published)
select courses.id, source.image_url, '자바 1-2 과정 상세 이미지', source.image_order, true
from public.courses
cross join (values
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Java/Java3.jpg', 0),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Java/Java4.jpg', 1),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Java/Java5.jpg', 2),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Java/Java6.jpg', 3),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Java/Java7.jpg', 4)
) as source(image_url, image_order)
where courses.name = '자바 1-2';

insert into public.course_images (course_id, image_url, alt_text, sort_order, is_published)
select courses.id, source.image_url, 'C언어 1-2 과정 상세 이미지', source.image_order, true
from public.courses
cross join (values
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/C/C3.jpg', 0),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/C/C4.jpg', 1),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/C/C5.jpg', 2),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/C/C6.jpg', 3),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/C/C7.jpg', 4),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/C/C8.jpg', 5),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/C/C9.jpg', 6)
) as source(image_url, image_order)
where courses.name = 'C언어 1-2';

insert into public.course_images (course_id, image_url, alt_text, sort_order, is_published)
select courses.id, source.image_url, 'Blender1-2 과정 상세 이미지', source.image_order, true
from public.courses
cross join (values
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Blender1-2/Blender2.jpg', 0),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Blender1-2/Blender3.jpg', 1),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Blender1-2/Blender4.jpg', 2),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Blender1-2/Blender5.jpg', 3),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Blender1-2/Blender6.jpg', 4)
) as source(image_url, image_order)
where courses.name = 'Blender1-2';

insert into public.course_images (course_id, image_url, alt_text, sort_order, is_published)
select courses.id, source.image_url, 'BIM1-2 과정 상세 이미지', source.image_order, true
from public.courses
cross join (values
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/BIM1-2/BIM3.jpg', 0),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/BIM1-2/BIM4.jpg', 1),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/BIM1-2/BIM5.jpg', 2),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/BIM1-2/BIM6.jpg', 3),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/BIM1-2/BIM7.jpg', 4),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/BIM1-2/BIM8.jpg', 5),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/BIM1-2/BIM9.jpg', 6),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/BIM1-2/BIM10.jpg', 7),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/BIM1-2/BIM11.jpg', 8)
) as source(image_url, image_order)
where courses.name = 'BIM1-2';

insert into public.course_images (course_id, image_url, alt_text, sort_order, is_published)
select courses.id, source.image_url, '포토샵 과정 상세 이미지', source.image_order, true
from public.courses
cross join (values
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Photoshop/Photoshop2.jpg', 0),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Photoshop/Photoshop3.jpg', 1),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Photoshop/Photoshop4.jpg', 2),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Photoshop/Photoshop5.jpg', 3)
) as source(image_url, image_order)
where courses.name = '포토샵';

insert into public.course_images (course_id, image_url, alt_text, sort_order, is_published)
select courses.id, source.image_url, '포토웍스 과정 상세 이미지', source.image_order, true
from public.courses
cross join (values
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Photoworks/Photoworks2.jpg', 0),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Photoworks/Photoworks3.jpg', 1),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Photoworks/Photoworks4.jpg', 2),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Photoworks/Photoworks5.jpg', 3)
) as source(image_url, image_order)
where courses.name = '포토웍스';

insert into public.course_images (course_id, image_url, alt_text, sort_order, is_published)
select courses.id, source.image_url, '퓨전360 1-2(이미지 준비중) 과정 상세 이미지', source.image_order, true
from public.courses
cross join (values
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Fusion360/Fusion360_2.jpg', 0),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Fusion360/Fusion360_3.jpg', 1),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Fusion360/Fusion360_4.jpg', 2),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Fusion360/Fusion360_5.jpg', 3),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Fusion360/Fusion360_6.jpg', 4),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Fusion360/Fusion360_7.jpg', 5)
) as source(image_url, image_order)
where courses.name = '퓨전360 1-2(이미지 준비중)';

insert into public.course_images (course_id, image_url, alt_text, sort_order, is_published)
select courses.id, source.image_url, '프리미어 과정 상세 이미지', source.image_order, true
from public.courses
cross join (values
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Premiere/Premiere2.jpg', 0),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Premiere/Premiere3.jpg', 1),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Premiere/Premiere4.jpg', 2),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Premiere/Premiere5.jpg', 3),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Premiere/Premiere6.jpg', 4),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Premiere/Premiere7.jpg', 5)
) as source(image_url, image_order)
where courses.name = '프리미어';

insert into public.course_images (course_id, image_url, alt_text, sort_order, is_published)
select courses.id, source.image_url, '유튜브 과정 상세 이미지', source.image_order, true
from public.courses
cross join (values
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/YouTube/YouTube3.jpg', 0),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/YouTube/YouTube4.jpg', 1),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/YouTube/YouTube5.jpg', 2),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/YouTube/YouTube6.jpg', 3),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/YouTube/YouTube7.jpg', 4),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/YouTube/YouTube8.jpg', 5),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/YouTube/YouTube9.jpg', 6)
) as source(image_url, image_order)
where courses.name = '유튜브';

insert into public.course_images (course_id, image_url, alt_text, sort_order, is_published)
select courses.id, source.image_url, '유튜브(영크리) 과정 상세 이미지', source.image_order, true
from public.courses
cross join (values
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/YouTube_Youngcry/YouTube_Youngcry3.jpg', 0),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/YouTube_Youngcry/YouTube_Youngcry4.jpg', 1),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/YouTube_Youngcry/YouTube_Youngcry5.jpg', 2),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/YouTube_Youngcry/YouTube_Youngcry6.jpg', 3),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/YouTube_Youngcry/YouTube_Youngcry7.jpg', 4),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/YouTube_Youngcry/YouTube_Youngcry8.jpg', 5),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/YouTube_Youngcry/YouTube_Youngcry9.jpg', 6),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/YouTube_Youngcry/YouTube_Youngcry10.jpg', 7),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/YouTube_Youngcry/YouTube_Youngcry11.jpg', 8)
) as source(image_url, image_order)
where courses.name = '유튜브(영크리)';

insert into public.course_images (course_id, image_url, alt_text, sort_order, is_published)
select courses.id, source.image_url, '유튜브(시니어) 과정 상세 이미지', source.image_order, true
from public.courses
cross join (values
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/YouTube_senior/YouTube_senior3.jpg', 0),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/YouTube_senior/YouTube_senior4.jpg', 1),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/YouTube_senior/YouTube_senior5.jpg', 2),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/YouTube_senior/YouTube_senior6.jpg', 3),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/YouTube_senior/YouTube_senior7.jpg', 4),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/YouTube_senior/YouTube_senior8.jpg', 5),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/YouTube_senior/YouTube_senior9.jpg', 6),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/YouTube_senior/YouTube_senior10.jpg', 7)
) as source(image_url, image_order)
where courses.name = '유튜브(시니어)';

insert into public.course_images (course_id, image_url, alt_text, sort_order, is_published)
select courses.id, source.image_url, '웹디자인개발기능사 과정 상세 이미지', source.image_order, true
from public.courses
cross join (values
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Skill_History_of_Web_Design_Development/Skill_History_of_Web_Design_Development2.jpg', 0),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Skill_History_of_Web_Design_Development/Skill_History_of_Web_Design_Development3.jpg', 1),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Skill_History_of_Web_Design_Development/Skill_History_of_Web_Design_Development4.jpg', 2)
) as source(image_url, image_order)
where courses.name = '웹디자인개발기능사';

insert into public.course_images (course_id, image_url, alt_text, sort_order, is_published)
select courses.id, source.image_url, '웹1-3 과정 상세 이미지', source.image_order, true
from public.courses
cross join (values
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/WEB/WEB3.jpg', 0),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/WEB/WEB4.jpg', 1),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/WEB/WEB5.jpg', 2),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/WEB/WEB6.jpg', 3),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/WEB/WEB7.jpg', 4),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/WEB/WEB8.jpg', 5),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/WEB/WEB9.jpg', 6),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/WEB/WEB10.jpg', 7),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/WEB/WEB11.jpg', 8),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/WEB/WEB12.jpg', 9),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/WEB/WEB13.jpg', 10),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/WEB/WEB14.jpg', 11)
) as source(image_url, image_order)
where courses.name = '웹1-3';

insert into public.course_images (course_id, image_url, alt_text, sort_order, is_published)
select courses.id, source.image_url, 'UIUX1-3 과정 상세 이미지', source.image_order, true
from public.courses
cross join (values
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/WEB/WEB15.jpg', 0),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/WEB/WEB16.jpg', 1),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/WEB/WEB17.jpg', 2),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/WEB/WEB18.jpg', 3),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/WEB/WEB19.jpg', 4),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/WEB/WEB20.jpg', 5),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/WEB/WEB21.jpg', 6),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/WEB/WEB22.jpg', 7),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/WEB/WEB23.jpg', 8)
) as source(image_url, image_order)
where courses.name = 'UIUX1-3';

insert into public.course_images (course_id, image_url, alt_text, sort_order, is_published)
select courses.id, source.image_url, '영상편집&유튜브편집제작(프리미어,에프터이펙트)실무자 양성과정 과정 상세 이미지', source.image_order, true
from public.courses
cross join (values
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Video_editing_and_YouTube_editing_production/Video_editing_and_YouTube_editing_production_(premier,effect)_training_course_for_practitioners2.jpg', 0),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Video_editing_and_YouTube_editing_production/Video_editing_and_YouTube_editing_production_(premier,effect)_training_course_for_practitioners3.jpg', 1),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Video_editing_and_YouTube_editing_production/Video_editing_and_YouTube_editing_production_(premier,effect)_training_course_for_practitioners4.jpg', 2),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Video_editing_and_YouTube_editing_production/Video_editing_and_YouTube_editing_production_(premier,effect)_training_course_for_practitioners5.jpg', 3),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Video_editing_and_YouTube_editing_production/Video_editing_and_YouTube_editing_production_(premier,effect)_training_course_for_practitioners6.jpg', 4),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Video_editing_and_YouTube_editing_production/Video_editing_and_YouTube_editing_production_(premier,effect)_training_course_for_practitioners7.jpg', 5),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Video_editing_and_YouTube_editing_production/Video_editing_and_YouTube_editing_production_(premier,effect)_training_course_for_practitioners8.jpg', 6),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Video_editing_and_YouTube_editing_production/Video_editing_and_YouTube_editing_production_(premier,effect)_training_course_for_practitioners9.jpg', 7),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Video_editing_and_YouTube_editing_production/Video_editing_and_YouTube_editing_production_(premier,effect)_training_course_for_practitioners10.jpg', 8),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Video_editing_and_YouTube_editing_production/Video_editing_and_YouTube_editing_production_(premier,effect)_training_course_for_practitioners11.jpg', 9),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Video_editing_and_YouTube_editing_production/Video_editing_and_YouTube_editing_production_(premier,effect)_training_course_for_practitioners12.jpg', 10),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Video_editing_and_YouTube_editing_production/Video_editing_and_YouTube_editing_production_(premier,effect)_training_course_for_practitioners13.jpg', 11),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Video_editing_and_YouTube_editing_production/Video_editing_and_YouTube_editing_production_(premier,effect)_training_course_for_practitioners14.jpg', 12),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Video_editing_and_YouTube_editing_production/Video_editing_and_YouTube_editing_production_(premier,effect)_training_course_for_practitioners15.jpg', 13),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Video_editing_and_YouTube_editing_production/Video_editing_and_YouTube_editing_production_(premier,effect)_training_course_for_practitioners16.jpg', 14),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Video_editing_and_YouTube_editing_production/Video_editing_and_YouTube_editing_production_(premier,effect)_training_course_for_practitioners17.jpg', 15),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Video_editing_and_YouTube_editing_production/Video_editing_and_YouTube_editing_production_(premier,effect)_training_course_for_practitioners18.jpg', 16),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Video_editing_and_YouTube_editing_production/Video_editing_and_YouTube_editing_production_(premier,effect)_training_course_for_practitioners19.jpg', 17),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Video_editing_and_YouTube_editing_production/Video_editing_and_YouTube_editing_production_(premier,effect)_training_course_for_practitioners20.jpg', 18),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Video_editing_and_YouTube_editing_production/Video_editing_and_YouTube_editing_production_(premier,effect)_training_course_for_practitioners21.jpg', 19)
) as source(image_url, image_order)
where courses.name = '영상편집&유튜브편집제작(프리미어,에프터이펙트)실무자 양성과정';

insert into public.course_images (course_id, image_url, alt_text, sort_order, is_published)
select courses.id, source.image_url, '어드벤스에펙 과정 상세 이미지', source.image_order, true
from public.courses
cross join (values
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Advances_Effec/Advances_Effec3.jpg', 0),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Advances_Effec/Advances_Effec4.jpg', 1),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Advances_Effec/Advances_Effec5.jpg', 2),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Advances_Effec/Advances_Effec6.jpg', 3)
) as source(image_url, image_order)
where courses.name = '어드벤스에펙';

insert into public.course_images (course_id, image_url, alt_text, sort_order, is_published)
select courses.id, source.image_url, '실무엑셀(금요특강)(이미지 준비중) 과정 상세 이미지', source.image_order, true
from public.courses
cross join (values
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Practical_Excel/Practical_Excel3.jpg', 0),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Practical_Excel/Practical_Excel4.jpg', 1),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Practical_Excel/Practical_Excel5.jpg', 2)
) as source(image_url, image_order)
where courses.name = '실무엑셀(금요특강)(이미지 준비중)';

insert into public.course_images (course_id, image_url, alt_text, sort_order, is_published)
select courses.id, source.image_url, '시네마4D 1-4 과정 상세 이미지', source.image_order, true
from public.courses
cross join (values
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Cinema4D/Cinema4D3.jpg', 0),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Cinema4D/Cinema4D4.jpg', 1),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Cinema4D/Cinema4D5.jpg', 2),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Cinema4D/Cinema4D6.jpg', 3),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Cinema4D/Cinema4D7.jpg', 4),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Cinema4D/Cinema4D8.jpg', 5),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Cinema4D/Cinema4D9.jpg', 6),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Cinema4D/Cinema4D10.jpg', 7),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Cinema4D/Cinema4D11.jpg', 8)
) as source(image_url, image_order)
where courses.name = '시네마4D 1-4';

insert into public.course_images (course_id, image_url, alt_text, sort_order, is_published)
select courses.id, source.image_url, '스토리보드 1-6 과정 상세 이미지', source.image_order, true
from public.courses
cross join (values
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Storyboard/Storyboard3.jpg', 0),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Storyboard/Storyboard4.jpg', 1),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Storyboard/Storyboard5.jpg', 2),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Storyboard/Storyboard6.jpg', 3),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Storyboard/Storyboard7.jpg', 4),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Storyboard/Storyboard8.jpg', 5),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Storyboard/Storyboard9.jpg', 6),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Storyboard/Storyboard10.jpg', 7),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Storyboard/Storyboard11.jpg', 8),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Storyboard/Storyboard12.jpg', 9),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Storyboard/Storyboard13.jpg', 10),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Storyboard/Storyboard14.jpg', 11),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Storyboard/Storyboard15.jpg', 12)
) as source(image_url, image_order)
where courses.name = '스토리보드 1-6';

insert into public.course_images (course_id, image_url, alt_text, sort_order, is_published)
select courses.id, source.image_url, '스토리보드1-6 과정 상세 이미지', source.image_order, true
from public.courses
cross join (values
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Storyboard/Storyboard3.jpg', 0),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Storyboard/Storyboard4.jpg', 1),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Storyboard/Storyboard5.jpg', 2),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Storyboard/Storyboard6.jpg', 3),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Storyboard/Storyboard7.jpg', 4),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Storyboard/Storyboard8.jpg', 5),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Storyboard/Storyboard9.jpg', 6),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Storyboard/Storyboard10.jpg', 7),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Storyboard/Storyboard11.jpg', 8),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Storyboard/Storyboard12.jpg', 9),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Storyboard/Storyboard13.jpg', 10),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Storyboard/Storyboard14.jpg', 11),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Storyboard/Storyboard15.jpg', 12)
) as source(image_url, image_order)
where courses.name = '스토리보드1-6';

insert into public.course_images (course_id, image_url, alt_text, sort_order, is_published)
select courses.id, source.image_url, '스케치업1-2 과정 상세 이미지', source.image_order, true
from public.courses
cross join (values
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Sketchup/Sketchup3.jpg', 0),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Sketchup/Sketchup4.jpg', 1),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Sketchup/Sketchup5.jpg', 2),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Sketchup/Sketchup6.jpg', 3),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Sketchup/Sketchup7.jpg', 4),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Sketchup/Sketchup8.jpg', 5),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Sketchup/Sketchup9.jpg', 6)
) as source(image_url, image_order)
where courses.name = '스케치업1-2';

insert into public.course_images (course_id, image_url, alt_text, sort_order, is_published)
select courses.id, source.image_url, '숏폼컨텐츠(금요특강) 과정 상세 이미지', source.image_order, true
from public.courses
cross join (values
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/ShortForm_Content/ShortForm_Content3.jpg', 0),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/ShortForm_Content/ShortForm_Content4.jpg', 1),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/ShortForm_Content/ShortForm_Content5.jpg', 2),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/ShortForm_Content/ShortForm_Content6.jpg', 3)
) as source(image_url, image_order)
where courses.name = '숏폼컨텐츠(금요특강)';

insert into public.course_images (course_id, image_url, alt_text, sort_order, is_published)
select courses.id, source.image_url, '색채학 과정 상세 이미지', source.image_order, true
from public.courses
cross join (values
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Color_Science/Color_Science3.jpg', 0),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Color_Science/Color_Science4.jpg', 1),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Color_Science/Color_Science5.jpg', 2),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Color_Science/Color_Science6.jpg', 3)
) as source(image_url, image_order)
where courses.name = '색채학';

insert into public.course_images (course_id, image_url, alt_text, sort_order, is_published)
select courses.id, source.image_url, '베이직에펙 과정 상세 이미지', source.image_order, true
from public.courses
cross join (values
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Basic_Effec/Basic_Effec3.jpg', 0),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Basic_Effec/Basic_Effec4.jpg', 1),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Basic_Effec/Basic_Effec5.jpg', 2),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Basic_Effec/Basic_Effec6.jpg', 3)
) as source(image_url, image_order)
where courses.name = '베이직에펙';

insert into public.course_images (course_id, image_url, alt_text, sort_order, is_published)
select courses.id, source.image_url, '디테일일러스트 과정 상세 이미지', source.image_order, true
from public.courses
cross join (values
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Detailed_Illustration/Detailed_Illustration2.jpg', 0),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Detailed_Illustration/Detailed_Illustration3.jpg', 1),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Detailed_Illustration/Detailed_Illustration4.jpg', 2),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Detailed_Illustration/Detailed_Illustration5.jpg', 3)
) as source(image_url, image_order)
where courses.name = '디테일일러스트';

insert into public.course_images (course_id, image_url, alt_text, sort_order, is_published)
select courses.id, source.image_url, '발상과 표현 과정 상세 이미지', source.image_order, true
from public.courses
cross join (values
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Ideas_and_Expressions/Ideas_and_Expressions3.jpg', 0),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Ideas_and_Expressions/Ideas_and_Expressions4.jpg', 1),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Ideas_and_Expressions/Ideas_and_Expressions5.jpg', 2),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Ideas_and_Expressions/Ideas_and_Expressions6.jpg', 3),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Ideas_and_Expressions/Ideas_and_Expressions7.jpg', 4)
) as source(image_url, image_order)
where courses.name = '발상과 표현';

insert into public.course_images (course_id, image_url, alt_text, sort_order, is_published)
select courses.id, source.image_url, '모스 과정 상세 이미지', source.image_order, true
from public.courses
cross join (values
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Moss/Moss3.jpg', 0),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Moss/Moss4.jpg', 1),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Moss/Moss5.jpg', 2),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Moss/Moss6.jpg', 3),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Moss/Moss7.jpg', 4)
) as source(image_url, image_order)
where courses.name = '모스';

insert into public.course_images (course_id, image_url, alt_text, sort_order, is_published)
select courses.id, source.image_url, '모션에펙 과정 상세 이미지', source.image_order, true
from public.courses
cross join (values
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Motion_Effec/Motion_Effec3.jpg', 0),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Motion_Effec/Motion_Effec4.jpg', 1),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Motion_Effec/Motion_Effec5.jpg', 2),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/Motion_Effec/Motion_Effec6.jpg', 3)
) as source(image_url, image_order)
where courses.name = '모션에펙';

insert into public.course_images (course_id, image_url, alt_text, sort_order, is_published)
select courses.id, source.image_url, '맥스 1-3 과정 상세 이미지', source.image_order, true
from public.courses
cross join (values
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/MAX/MAX3.jpg', 0),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/MAX/MAX4.jpg', 1),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/MAX/MAX5.jpg', 2),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/MAX/MAX6.jpg', 3),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/MAX/MAX7.jpg', 4),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/MAX/MAX8.jpg', 5),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/MAX/MAX9.jpg', 6),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/MAX/MAX10.jpg', 7),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/MAX/MAX11.jpg', 8),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/MAX/MAX12.jpg', 9)
) as source(image_url, image_order)
where courses.name = '맥스 1-3';

insert into public.course_images (course_id, image_url, alt_text, sort_order, is_published)
select courses.id, source.image_url, '마야크리틱(포폴기획 - 금요특강) 과정 상세 이미지', source.image_order, true
from public.courses
cross join (values
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/MayaCritic/MayaCritic2.jpg', 0),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/MayaCritic/MayaCritic3.jpg', 1),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/MayaCritic/MayaCritic4.jpg', 2),
    ('https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/MayaCritic/MayaCritic5.jpg', 3)
) as source(image_url, image_order)
where courses.name = '마야크리틱(포폴기획 - 금요특강)';

insert into public.curriculum_shortcuts (label, title, description_lines, target_category_slug, aria_label, sort_order, is_published) values
    ('AI Master', 'AI Master', array['AI 자동화, 바이브코딩']::text[], 'ai_agent', 'AI Master 교육과정 바로가기', 0, true),
    ('HOT', 'AI 디자인', array['AI 디자인', '웹 UIUX, 시각편집']::text[], 'uiux', 'AI 디자인 교육과정 바로가기', 1, true),
    ('AI 모션·CG', 'AI 모션/CG', array['유튜브/영상편집']::text[], 'motion', 'AI 모션·CG 교육과정 바로가기', 2, true),
    ('AI 웹툰/드로잉', 'AI 웹툰/드로잉', array['미술 기초, 디지털드로잉']::text[], 'webtoon', 'AI 웹툰·드로잉 교육과정 바로가기', 3, true),
    ('AI 인테리어', 'AI 인테리어/제품', array['인테리어/기계,제품']::text[], 'archi', 'AI 인테리어·제품 교육과정 바로가기', 4, true),
    ('AI 자격증', '자격증', array['디자인/사무/AI자격증']::text[], 'cert', 'AI 자격증 교육과정 바로가기', 5, true);

insert into public.portfolio_items (thumbnail_url, detail_image_url, alt_text, sort_order, is_published) values
    ('https://cdn.koreaedugroup.com/sbsfile/gallery_img/%EC%9D%B8%EB%A7%88%EB%A6%AC%EC%95%84,%20%EB%B0%B0%EB%AF%B8%EB%82%98,%20%EB%B0%95%EC%86%8C%ED%98%B8,%20%EC%8B%AC%EC%9C%A0%EB%82%98%20%EC%8D%B8%EB%84%A4%EC%9D%BC.jpg', 'https://cdn.koreaedugroup.com/sbsfile/gallery_img/%EC%9D%B8%EB%A7%88%EB%A6%AC%EC%95%84,%20%EB%B0%B0%EB%AF%B8%EB%82%98,%20%EB%B0%95%EC%86%8C%ED%98%B8,%20%EC%8B%AC%EC%9C%A0%EB%82%98%20%EB%B3%B8%EB%AC%B8.jpg', '수강생 작품', 0, true),
    ('https://cdn.koreaedugroup.com/sbsfile/gallery_img/(%EA%B0%95%EC%98%88%EB%A6%AC,%20%EA%B9%80%EB%AF%BC%EC%B2%B4,%20%EC%9B%90%EC%98%88%EC%A7%80,%20%EA%B9%80%EB%8F%84%EC%97%B0)%20%EC%8D%B8%EB%84%A4%EC%9D%BC-1.jpg', 'https://cdn.koreaedugroup.com/sbsfile/gallery_img/(%EA%B0%95%EC%98%88%EB%A6%AC,%20%EA%B9%80%EB%AF%BC%EC%B2%B4,%20%EC%9B%90%EC%98%88%EC%A7%80,%20%EA%B9%80%EB%8F%84%EC%97%B0)%20%EC%8D%B8%EB%84%A4%EC%9D%BC.jpg', '수강생 작품', 1, true),
    ('https://cdn.koreaedugroup.com/sbsfile/gallery_img/%EC%9D%B8%EB%A7%88%EB%A6%AC%EC%95%84%20%EC%8D%B8%EB%84%A4%EC%9D%BC.png', 'https://cdn.koreaedugroup.com/sbsfile/gallery_img/%EC%9D%B8%EB%A7%88%EB%A6%AC%EC%95%84%20%EB%B3%B8%EB%AC%B8(0).jpg', '수강생 작품', 2, true),
    ('https://cdn.koreaedugroup.com/sbsfile/gallery_img/%EA%B9%80%EA%B2%BD%EC%9D%80,%20%EC%9C%A4%EC%84%B1%EB%AF%BC_%EC%8D%B8%EB%84%A4%EC%9D%BC.jpg', 'https://cdn.koreaedugroup.com/sbsfile/gallery_img/%EA%B9%80%EA%B2%BD%EC%9D%80,%20%EC%9C%A4%EC%84%B1%EB%AF%BC_%EB%B3%B8%EB%AC%B8.jpg', '수강생 작품', 3, true),
    ('https://cdn.koreaedugroup.com/sbsfile/gallery_img/%EA%B9%80%EC%88%98%EB%B9%88,%20%EB%B0%95%EC%9D%80%EB%B9%84,%20%EC%9C%A4%ED%83%9D%ED%95%9C_%EC%8D%B8%EB%84%A4%EC%9D%BC.jpg', 'https://cdn.koreaedugroup.com/sbsfile/gallery_img/%EA%B9%80%EC%88%98%EB%B9%88,%20%EB%B0%95%EC%9D%80%EB%B9%84,%20%EC%9C%A4%ED%83%9D%ED%95%9C_%EB%B3%B8%EB%AC%B8.jpg', '수강생 작품', 4, true),
    ('https://cdn.koreaedugroup.com/sbsfile/gallery_img/%EA%B9%80%EC%9C%A0%EC%8B%A0,%20%EB%82%98%EC%9C%A4%ED%95%98,%20%EC%9E%84%EC%86%8C%EC%97%B0_%EC%8D%B8%EB%84%A4%EC%9D%BC.jpg', 'https://cdn.koreaedugroup.com/sbsfile/gallery_img/%EA%B9%80%EC%9C%A0%EC%8B%A0,%20%EB%82%98%EC%9C%A4%ED%95%98,%20%EC%9E%84%EC%86%8C%EC%97%B0_%EB%B3%B8%EB%AC%B8.jpg', '수강생 작품', 5, true),
    ('https://cdn.koreaedugroup.com/sbsfile/gallery_img/%EC%86%A1%EB%A7%8C%EA%B8%B0%20%EC%8D%B8%EB%84%A4%EC%9D%BC.jpg', 'https://cdn.koreaedugroup.com/sbsfile/gallery_img/%EC%86%A1%EB%A7%8C%EA%B8%B0%20%EB%B3%B8%EB%AC%B8.jpg', '수강생 작품', 6, true),
    ('https://cdn.koreaedugroup.com/sbsfile/gallery_img/%EC%8D%B8%EB%84%A4%EC%9D%BC%20400300.jpg', 'https://cdn.koreaedugroup.com/sbsfile/gallery_img/%EB%B3%B8%EB%AC%B8%201000(0).jpg', '수강생 작품', 7, true),
    ('https://cdn.koreaedugroup.com/sbsfile/gallery_img/SBS_portfolio_thumb(610).jpg', 'https://cdn.koreaedugroup.com/sbsfile/gallery_img/portfolio3.jpg', '수강생 작품', 8, true),
    ('https://cdn.koreaedugroup.com/sbsfile/gallery_img/%EC%9E%84%EB%8B%A4%ED%98%9C%20%EC%8D%B8%EB%84%A4%EC%9D%BC.jpg', 'https://cdn.koreaedugroup.com/sbsfile/gallery_img/%EC%9E%84%EB%8B%A4%ED%98%9C%20%EB%B3%B8%EB%AC%B8.jpg', '수강생 작품', 9, true),
    ('https://cdn.koreaedugroup.com/sbsfile/gallery_img/%EB%B0%B0%EC%88%98%EC%97%B0%20%EC%8D%B8%EB%84%A4%EC%9D%BC.jpg', 'https://cdn.koreaedugroup.com/sbsfile/gallery_img/%EB%B0%B0%EC%88%98%EC%97%B0%20%EB%B3%B8%EB%AC%B8.jpg', '수강생 작품', 10, true),
    ('https://cdn.koreaedugroup.com/sbsfile/gallery_img/%EA%B9%80%EB%AF%BC%EC%86%94%20%EC%8D%B8%EB%84%A4%EC%9D%BC.jpg', 'https://cdn.koreaedugroup.com/sbsfile/gallery_img/%EA%B9%80%EB%AF%BC%EC%86%94%20%EB%B3%B8%EB%AC%B8.jpg', '수강생 작품', 11, true),
    ('https://cdn.koreaedugroup.com/sbsfile/gallery_img/%EC%97%84%EB%AF%BC%EC%84%AD%20%EC%8D%B8%EB%84%A4%EC%9D%BC.jpg', 'https://cdn.koreaedugroup.com/sbsfile/gallery_img/%EC%97%84%EB%AF%BC%EC%84%AD%20%EB%B3%B8%EB%AC%B8.jpg', '수강생 작품', 12, true),
    ('https://cdn.koreaedugroup.com/sbsfile/gallery_img/%EA%B3%A0%EC%96%B8%EC%A0%95%20%EC%8D%B8%EB%84%A4%EC%9D%BC.jpg', 'https://cdn.koreaedugroup.com/sbsfile/gallery_img/%EA%B3%A0%EC%96%B8%EC%A0%95%20%EB%B3%B8%EB%AC%B8.jpg', '수강생 작품', 13, true),
    ('https://cdn.koreaedugroup.com/sbsfile/gallery_img/%EC%8B%AC%ED%9A%A8%EC%9D%80%20%EC%8D%B8%EB%84%A4%EC%9D%BC.jpg', 'https://cdn.koreaedugroup.com/sbsfile/gallery_img/%EC%8B%AC%ED%9A%A8%EC%9D%80%20%EB%B3%B8%EB%AC%B8.jpg', '수강생 작품', 14, true),
    ('https://cdn.koreaedugroup.com/sbsfile/gallery_img/%EC%8B%AC%ED%9A%A8%EC%9D%80%20%EB%B3%B8%EB%AC%B8(0).jpg', 'https://cdn.koreaedugroup.com/sbsfile/gallery_img/%EC%8B%AC%ED%9A%A8%EC%9D%80%20%EB%B3%B8%EB%AC%B8(0).jpg', '수강생 작품', 15, true),
    ('https://cdn.koreaedugroup.com/sbsfile/gallery_img/%EB%B0%95%ED%98%84%EC%A0%95%20%EC%8D%B8%EB%84%A4%EC%9D%BC1.jpg', 'https://cdn.koreaedugroup.com/sbsfile/gallery_img/%EB%B0%95%ED%98%84%EC%A0%95%20%EB%B3%B8%EB%AC%B81.jpg', '수강생 작품', 16, true),
    ('https://cdn.koreaedugroup.com/sbsfile/gallery_img/%EC%9C%A0%EC%86%8C%EC%9D%B4%20%EC%8D%B8%EB%84%A4%EC%9D%BC.jpg', 'https://cdn.koreaedugroup.com/sbsfile/gallery_img/%EC%9C%A0%EC%86%8C%EC%9D%B4%20%EB%B3%B8%EB%AC%B8.jpg', '수강생 작품', 17, true);

insert into public.review_items (kind, label, title, body, course_name, author_name, year_label, sort_order, is_published) values
    ('hero', '수강생 취업자 특강', '"SBS아카데미컴퓨터아트학원 대전지점 취업자 현직자 특강"', '[컴퓨터 대전] UIUX 현직자 특강', null, '김선민', '2026', 0, true),
    ('item', '취업생 인터뷰', null, '"학원에서의 배움을 토대로 현재 디자이너로서 다양한 경험을 하고 있습니다."', '[대전] 웹디자인', '임예나', null, 1, true),
    ('item', '취업생 인터뷰', null, '"자소서 작성이나 포트폴리오를 준비할 때에도 첨삭과 피드백을 받을 수 있어 큰 도움이 되었습니다."', '[대전] 광고편집', '최해인', null, 2, true),
    ('item', '수강생 인터뷰', null, '"비전공자도 아트에 관련한 직무 역량을 기초부터 쌓을 수 있도록 체계적으로 커리큘럼이 갖춰져 있다고 느꼈습니다."', '[대전] CG', '김동권', null, 3, true),
    ('item', '수강생 인터뷰', null, '"일단 훌륭한 강사님께서 수강생 한 명, 한 명의 수준과 속도에 최대한 맞춰가면서 수업을 진행해주신 점이 도움이 되지 않았나 싶습니다."', '[대전] 모션그래픽', '강대솔', null, 4, true);

insert into public.seminars (branch, title, description, event_date_label, application_period_label, image_url, background_class, sort_order, is_published) values
    ('[대전지점]', '인스타툰으로 시작하는 나만의 콘텐츠 브랜딩 세미나', '퍼스널 브랜딩부터 실전 드로잉, 채널 성장 노하우까지 현업 작가에게 직접 배웁니다.', '2026. 04. 29 (수) 16:00', '2026. 04. 01 ~ 2026. 04. 28', 'https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/seminar/seminar1.jpg', 'poster-lilac', 0, true),
    ('[대전지점]', 'AI가 대신 일하는 시대, AI에이전트 실전 세미나', 'Claude Code로 만드는 자동화 워크플로우 실무 활용 및 확장 전략을 배웁니다.', '2026. 04. 30 (목) 14:00 - 16:00', '2026. 04. 01 ~ 2026. 04. 29', 'https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/seminar/seminar2.jpg', 'poster-night', 1, true),
    ('[대전지점]', '인테리어 AI 크리에이터 신규과정 런칭', '신규과정 소개와 인테리어 분야에서의 AI전망 및 연계 방법을 알아봅니다.', '2025. 11. 28 (금) 13:00 - 15:00', '~ 2025. 11. 27', 'https://cdn.jsdelivr.net/gh/sbsweb35-tech/SBS@main/seminar/seminar3.jpg', 'poster-clay', 2, true);

commit;
